const express = require('express')
const cors=require('cors')
const app = express()
app.use(cors())
app.use(express.urlencoded({ extended: false }))
app.listen(80,()=> console.log('启动在http://127.0.0.1'))